# Generated by Django 4.1.7 on 2023-03-18 08:31

import coedinator.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0002_cordinatorregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=50)),
                ('Event_Description', models.CharField(blank=True, max_length=120, null=True)),
                ('Event_Date', models.DateField()),
                ('Event_Time', models.TimeField()),
                ('Event_Banner', models.ImageField(blank=True, null=True, upload_to='event_banner')),
                ('for_visitors', models.BooleanField(default=False)),
                ('Event_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cordinatorregister')),
                ('volunteers', models.ManyToManyField(to='register.studentregister')),
            ],
        ),
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=80)),
                ('Description', models.CharField(max_length=120)),
                ('Place', models.CharField(max_length=120)),
                ('DateAndTime', models.DateTimeField()),
                ('video', models.FileField(blank=True, null=True, upload_to='event_video/')),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Gender', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{9,10}$')])),
                ('description', models.CharField(max_length=120)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coedinator.event')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Gender', models.CharField(max_length=12)),
                ('Institute', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{9,10}$')])),
                ('field', models.CharField(max_length=80)),
                ('semester', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coedinator.event')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=coedinator.models.get_image_filename, verbose_name='Image')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coedinator.pastevent')),
            ],
        ),
    ]
